/*laboratorio 1
delivereres */

/*Q1*/
SELECT * FROM DELIVERERS;

/*Q2*/
SELECT DISTINCT COMPANYID FROM COMPANYDEL;

/*Q3*/
SELECT NAME , DELIVERERID
FROM DELIVERERS
WHERE NAME LIKE 'B%';

/*Q4*/
SELECT NAME , SEX , DELIVERERID
FROM DELIVERERS
WHERE PHONENO <> 8467 OR PHONENO IS NULL
;

/*5*/
SELECT D.NAME , D.TOWN 
FROM DELIVERERS D , PENALTIES P
WHERE D.DELIVERERID=P.DELIVERERID;

/*6*/
/*
SELECT D.NAME , D.INITIALS
FROM DELIVERERS D,PENALTIES P,COMPANIES C
WHERE D.DELIVERERID=P.DELIVERERID AND P.DELIVERERID=C.DELIVERERID AND P.DATA>TO_DATE('31/12/1980','DD/MM/AAAA')
ORDER BY D.NAME
;
*//*PROF SOLOUTION
SELECT DISTINCT NAME , INITIALS
FROM DELIVERERS D , PENALTIES P, COMPANIES C
WHERE D.DELIVERERID=P.DELIVERERID AND C.DELIVERERID=P.DELIVERERID AND DATA>TO_DATE('31/12/1980','DD/MM/AAAA')
ORDER BY NAME; 
*/

/*Q7*/
SELECT *
FROM COMPANYDEL C , DELIVERERS D
WHERE D.DELIVERERID=C.DELIVERERID AND D.TOWN='Stratford' 
AND NUMCOLLECTIONS >=2 AND C.NUMDELIVERIES>=1;

/*Q8*/
SELECT D.DELIVERERID
FROM DELIVERERS D , COMPANIES C , COMPANYDEL W
WHERE D.YEAR_OF_BIRTH>1962 AND C.MANDATE='first' 
AND C.COMPANYID=W.COMPANYID AND W.DELIVERERID=D.DELIVERERID
GROUP BY D.DELIVERERID;

/*Q9*/
SELECT D.NAME
FROM DELIVERERS D, COMPANYDEL C
WHERE (D.TOWN='Stratford' OR D.TOWN='Inglewood')
GROUP BY C.DELIVERERID,D.NAME
HAVING COUNT(*)>1
;

/*Q10*/
SELECT P.DELIVERERID,SUM(P.AMOUNT)
FROM PENALTIES P, DELIVERERS D
WHERE P.DELIVERERID=D.DELIVERERID AND D.TOWN='Inglewood'
GROUP BY P.DELIVERERID
HAVING COUNT(*)>=2
;

/*Q11*/
SELECT D.NAME , MIN(P.AMOUNT)
FROM DELIVERERS D , PENALTIES P
WHERE D.DELIVERERID=P.DELIVERERID
GROUP BY D.DELIVERERID ,D.NAME
HAVING COUNT(*)>=2 AND COUNT(*)<=4
;

/*Q12*/
SELECT SUM(C.NUMDELIVERIES),SUM(C.NUMCOLLECTIONS)
FROM COMPANYDEL C, DELIVERERS D
WHERE C.DELIVERERID=D.DELIVERERID AND D.TOWN<>'Stratford' AND D.NAME LIKE 'B%'
;